name: Build
on:
  push:
    branches: ["master"]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "25"
          distribution: "zulu"
          cache: maven
      - name: Build with Maven
        run: mvn -B package

      - name: Postprocess
        run: mv target/openrhynn-1.0-SNAPSHOT.jar ./openrhynn.jar

      - name: Checkout content
        uses: actions/checkout@v6
        with:
          repository: steel-team/OpenrhynnServerContent
          path: build
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare full release
        run: |
          cp openrhynn.jar build/openrhynn.jar
          cp -r database build
          cd build
          zip -r ../artifact.zip .

      - name: Set short git commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: |
            artifact.zip
            openrhynn.jar

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.vars.outputs.sha_short }}
          files: |
            artifact.zip
            openrhynn.jar
